server:
  port : 8088

spring:
  h2:
    console:
      enabled: true
#  boot:
#    enableautoconfiguration: false
#
#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: ERROR